### ISSUE TITLE
Save votes to database

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/api#39]
Need to find a suitable way to represent votes for a poll in Postgres.  Key features:
- Host should be able to retrieve **sum of all votes** for each category/option
- **Trace vote back to the invitee**.  Invitees have the option of changing their mind, so need to keep track of what they voted

**Comment by minaorangina** [comment]
## Representation options
### Votes table

- one row represents one invitee's votes for a particular event
- one column per category (what, where, when)
- category: array of votes (0 or 1) or` NULL` if no options available for that category

```json
{
  "event_id": 1,
  "what": ["dancing", "bowling"],
  "where": ["Shoreditch", "Angel", "Southwark"],
  "when": ["2017-02-30T18:00:00.000Z"],
  "votes": {
    "what": [2, 2],
    "where": [2, 0, 1],
    "when": []
  }
}

```
#### `votes` table
| event_id  | user_id  | what  | where  | when  |
|:-:|:-:|:-:|:-:|:-:|
| 1  | 3  | '{1, 1}'  | '{1, 0, 0}'  |  null |
| 1  | 5  | '{0, 1}'  | '{0, 0, 1}'  |  null |
| 1  |  8 |  '{1, 0}' | '{1, 0, 0}'  |  null |

To get one invitee's votes:
```bash
SELECT * FROM votes WHERE user_id = 5 AND event_id = 1;
```

To get the sum of all votes:
most likely some nested queries resulting in the `SUM()` aggregate function being run on the values

**Comment by heron2014** [comment]
### Save vote if not exist else update 

```bash
INSERT INTO votes (user_id, event_id, _what, _when) 
  VALUES ($1, $2, $3, $4)
  ON CONFLICT (user_id, event_id)
  DO UPDATE
  SET _what = $3, _when = $4
  WHERE user_id = $1 AND event_id = $2
```
