### ISSUE TITLE
make PATCH event/invitees more RESTful

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/api#48]
#23 #26

**Comment by minaorangina** [comment]
Due to the change in db structure for invitees, the `PATCH` verb is no longer correct.
Relates to #46

**Comment by minaorangina** [comment]
For the sake of consistency, will go for
`POST events/rsvps` (when someone enters their code and joins event for first time)
which will be in line with
`PATCH events/:event_id/rsvps` (when someone says if their coming/not coming to an event

**Comment by heron2014** [comment]
@minaorangina 
what about when someone enters their code for the first time: ```POST events/:event_id/rsvps``` ?

and the second one is ```PATCH```

**Comment by minaorangina** [comment]
@heron2014 first time someone enters code: 
`POST events/rsvps` - we won't have the event_id until the event is found by the code in the backend
the second one is `PATCH` because by the time someone says if they're going/not going, an entry in the database will exist for them already.  So they'll be `PATCH`ing their previous rsvp table entry

**Comment by heron2014** [comment]
@minaorangina yes of course, forgot about the id. In regards to PATCH I have agreed before :)

**Comment by heron2014** [comment]
Resolved by #51
