### ISSUE TITLE
Create database structure

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/api#6]
http://ondras.zarovi.cz/sql/demo/

**Comment by minaorangina** [comment]
### Arrays
[Postgres Guide](http://postgresguide.com/cool/arrays.html)

**Comment by minaorangina** [comment]
### JSON
You can take data from a row and have it returned to you in JSON.  [See here](https://wiki.postgresql.org/wiki/What's_new_in_PostgreSQL_9.2#JSON_datatype)

**Comment by heron2014** [comment]
Storing phone number 

Reference:
https://en.wikipedia.org/wiki/E.123
